### ISSUE TITLE
Duplicate census tract IDs

### ISSUE THREAD

**Issue by lhdatalab** [datakind/Mar21-housing-insecurity#24]
The nyc_acs5-2018_census.csv file has duplicate census tracts for different counties. E.g census tract 200.
nyc_tax_lien_sale_list_geocoded_benchmark4vintage410.csv on the google drive also reflects this.
When merging data it can't be done by census tract alone it has to be done by census and county or by GEOID.

**Comment by DMW2151** [comment]
@lhdatalab - Is there sufficient data to do all the joins required? i.e. does each dataset that identifies by the shorter tract ID  (e.g. 200 instead of 360541200) have the data to create the full long ID?

**Comment by snnehete** [comment]
Made a file nyc_tax_lien_sale_list_processed_acs.csv.gz file from nyc_tax_lien_sale_list_geocoded_benchmark4vintage410.csv including a column for GEOID which are unique. Also merged it with nyc_processed_2017_to_2019_20210225.csv for predictive modeling use. Added it to _volunteer_created_datasets.

**Comment by DMW2151** [comment]
closed by: https://github.com/datakind/Mar21-housing-insecurity/pull/29
documentation updated by: <pending>
